# Generated by Django 3.0.1 on 2020-01-09 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_auto_20200104_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dictionary',
            options={'verbose_name_plural': 'Dictionaries'},
        ),
        migrations.RemoveField(
            model_name='dictionary',
            name='case',
        ),
        migrations.RemoveField(
            model_name='dictionary',
            name='type',
        ),
        migrations.AddField(
            model_name='dictionary',
            name='maxItems',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='minItems',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='ChoiceRange',
        ),
        migrations.AddField(
            model_name='feature',
            name='dictionary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionaries.Dictionary'),
        ),
    ]
