# Generated by Django 3.0.2 on 2020-01-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0002_auto_20200109_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='comment',
            field=models.CharField(help_text='Comment for collection.', max_length=256, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='expired_on',
            field=models.DateTimeField(help_text='An expiration date of collection.', verbose_name='An expiration date'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='public',
            field=models.BooleanField(default=False, help_text='Make public.', verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='query',
            field=models.CharField(help_text='Query for collection.', max_length=256, verbose_name='Query'),
        ),
    ]
