# Generated by Django 3.0.3 on 2020-03-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0004_auto_20200221_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='name',
            field=models.CharField(default='default-name', help_text="Collection's name.", max_length=256, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='comment',
            field=models.CharField(blank=True, help_text='Comment for collection.', max_length=256, verbose_name='Comment'),
        ),
    ]
