# Generated by Django 3.0.5 on 2020-04-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('collections', '0006_auto_20200423_1831'), ('collections', '0007_auto_20200423_1843')]

    dependencies = [
        ('collections', '0005_auto_20200308_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='comment',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='query',
            new_name='queries',
        ),
        migrations.AlterField(
            model_name='collection',
            name='comments',
            field=models.CharField(blank=True, help_text='Comments for collection.', max_length=256, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='queries',
            field=models.CharField(help_text='Queries for collection.', max_length=256, verbose_name='Queries'),
        ),
    ]
