# Generated by Django 3.0.5 on 2020-04-23 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0005_auto_20200308_2239'),
    ]

    operations = [
        migrations.RenameField(model_name='collection', old_name='comment', new_name='comments'),
        migrations.RenameField(model_name='collection', old_name='query', new_name='queries'),
    ]
