# Generated by Django 3.0.6 on 2020-05-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0006_Plural_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='queries',
        ),
        migrations.AddField(
            model_name='collection',
            name='comment',
            field=models.CharField(blank=True, help_text='Comment for collection.', max_length=256, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='collection',
            name='query',
            field=models.CharField(default='', help_text='Query for collection.', max_length=256, verbose_name='Query'),
            preserve_default=False,
        ),
    ]
