# Generated by Django 3.0.7 on 2020-06-26 08:28

from django.db import migrations
import small_eod.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', small_eod.users.models.CustomUserManager()),
            ],
        ),
    ]
