# Generated by Django 3.0.1 on 2020-01-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_auto_20200109_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
