# Generated by Django 3.0.2 on 2020-01-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_auto_20200110_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='city',
            field=models.BooleanField(default=False, help_text='Name of city in institution address is mandatory for this channel.', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='email',
            field=models.BooleanField(default=False, help_text='Institution e-mail address is mandatory for this channel.', verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='epuap',
            field=models.BooleanField(default=False, help_text='Institution ePUAP address is mandatory for this channel.', verbose_name='ePUAP'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='flat_no',
            field=models.BooleanField(default=False, help_text='Flat number in institution address is mandatory for this channel.', verbose_name='Flat number'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='house_no',
            field=models.BooleanField(default=False, help_text='House number in institution address is mandatory for this channel.', verbose_name='House number'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(help_text="Channel's name. Name cannot be longer than 25 characters.", max_length=25, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='postal_code',
            field=models.BooleanField(default=False, help_text='Postal code in institution address is mandatory for this channel.', verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='street',
            field=models.BooleanField(default=False, help_text='Name of street in institution address is mandatory for this channel.', verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='voivodeship',
            field=models.BooleanField(default=False, help_text='Voivodeship in institution address is mandatory for this channel.', verbose_name='Voivodeship'),
        ),
    ]
