# Generated by Django 3.0.2 on 2020-01-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_auto_20200125_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(help_text="Channel's name.", max_length=25, verbose_name='Name'),
        ),
    ]
