# Generated by Django 3.0.3 on 2020-03-10 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureoption',
            name='feature',
            field=models.ForeignKey(help_text='Related feature.', on_delete=django.db.models.deletion.CASCADE, related_name='featureoptions', to='features.Feature', verbose_name='Feature'),
        ),
    ]
