# Generated by Django 3.0.5 on 2020-05-01 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('features', '0003_auto_20200501_0928'), ('features', '0004_auto_20200501_0935')]

    dependencies = [
        ('features', '0002_auto_20200310_0428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featureoption',
            old_name='feature',
            new_name='features',
        ),
        migrations.AlterField(
            model_name='featureoption',
            name='features',
            field=models.ForeignKey(help_text='Related features.', on_delete=django.db.models.deletion.CASCADE, related_name='featureoptions', to='features.Feature', verbose_name='Features'),
        ),
    ]
