labelPRBasedOnFilePath:
  front-end: 
    - 'frontend-project/**'
  back-end: 
    - 'backend-project/**'
  ci: 
    - '.github/**'
    - Makefile
    - docker-compose.yml
    - '**/Dockerfile'
  docs:
    - '**.md'
    - '**.rst'
    - 'docs/**'
