labelPRBasedOnFilePath:
  front-end: 
    - 'frontend-project/**'
  front-end-deps:
    - 'frontend-project/yarn.lock'
    - 'frontend-project/package.json'
  back-end: 
    - 'backend-project/**'
  back-end-deps:
    - 'backend-project/requirements/**'
  ci: 
    - '.github/**'
    - Makefile
    - docker-compose.yml
    - '**/Dockerfile'
  docs:
    - '**.md'
    - '**.rst'
    - 'docs/**'
