# Generated by Django 2.2.9 on 2019-12-28 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0013_auto_20190302_0518'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('notified', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=254, unique=True)),
                ('subject', models.CharField(default='{event_type_name} - {name}', max_length=254)),
                ('message', models.TextField(default='{name}', max_length=254)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.Case')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.EventType')),
            ],
        ),
    ]
