# Generated by Django 3.0.1 on 2020-01-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifiedOn', models.DateTimeField(auto_now=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(choices=[('FED', 'fedrowanie'), ('FAX', 'faks'), ('CUS', 'od klienta'), ('MEC', 'mecenas zewnętrzny'), ('PER', 'dostarczenie osobiste'), ('EMAIL', 'email'), ('POST', 'poczta tradycyjna'), ('EPUAP', 'epuap')], default='EMAIL', max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Required',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.BooleanField()),
                ('voivodeship', models.BooleanField()),
                ('flat_no', models.BooleanField()),
                ('street', models.BooleanField()),
                ('postal_code', models.BooleanField()),
                ('house_no', models.BooleanField()),
                ('email', models.BooleanField()),
                ('epuap', models.BooleanField()),
            ],
        ),
    ]
