# Generated by Django 3.0.1 on 2020-01-09 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionaries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0001_initial'),
        ('cases', '0002_case_auditedinstitution'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='case_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='feature',
            field=models.ManyToManyField(blank=True, to='dictionaries.Feature'),
        ),
        migrations.AddField(
            model_name='case',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='case_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='notified_user',
            field=models.ManyToManyField(blank=True, related_name='case_notified_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='responsible_user',
            field=models.ManyToManyField(blank=True, related_name='case_responsible_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='tag',
            field=models.ManyToManyField(blank=True, to='tags.Tag'),
        ),
    ]
