# Generated by Django 3.0.2 on 2020-01-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_auto_20200112_2019'),
        ('cases', '0003_auto_20200109_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='audited_institution',
            field=models.ManyToManyField(blank=True, help_text='Case audits this Institution', to='institutions.Institution'),
        ),
    ]
