# Generated by Django 3.0.2 on 2020-01-22 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_auto_20200112_2019'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0003_tagnamespace_prefix'),
        ('dictionaries', '0002_auto_20200109_1348'),
        ('cases', '0004_auto_20200114_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='audited_institution',
            field=models.ManyToManyField(blank=True, help_text='Case audits this Institution.', to='institutions.Institution', verbose_name='Audited institution'),
        ),
        migrations.AlterField(
            model_name='case',
            name='comment',
            field=models.CharField(help_text='Comment cannot be longer than 256 characters.', max_length=256, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='case',
            name='feature',
            field=models.ManyToManyField(blank=True, help_text='Features for this case.', to='dictionaries.Feature', verbose_name='Feature'),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(help_text="Case's name. Name cannot be longer than 256 characters.", max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='case',
            name='notified_user',
            field=models.ManyToManyField(blank=True, help_text='User who will receive notification.', related_name='case_notified_user', to=settings.AUTH_USER_MODEL, verbose_name='Notified user'),
        ),
        migrations.AlterField(
            model_name='case',
            name='responsible_user',
            field=models.ManyToManyField(blank=True, help_text='User who is responsible for this case.', related_name='case_responsible_user', to=settings.AUTH_USER_MODEL, verbose_name='Responsible user'),
        ),
        migrations.AlterField(
            model_name='case',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='Choose tag.', to='tags.Tag', verbose_name='Tag'),
        ),
    ]
