# Generated by Django 2.0.5 on 2018-06-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_auto_20180613_1042"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dictionary",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="dictionary",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "Whose case"),
                    (2, "What scope"),
                    (3, "Inaction scope"),
                    (4, "Decision scope"),
                    (5, "The moment of providing information"),
                    (6, "Proceedings interrupted"),
                    (7, "Status"),
                ],
                verbose_name="Type",
            ),
        ),
    ]
