# Generated by Django 3.0.2 on 2020-01-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20200122_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='comment',
            field=models.CharField(help_text='Comment for this case.', max_length=256, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(help_text="Case's name.", max_length=256, verbose_name='Name'),
        ),
    ]
