# Generated by Django 3.0.3 on 2020-03-15 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_case_featureoptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='comment',
            new_name='comments',
        ),
    ]
