# Generated by Django 3.0.5 on 2020-04-20 07:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cases', '0009_case_featureoptions'),
    ]

    operations = [
        migrations.RenameField(model_name='case', old_name='comment', new_name='comments'),
        migrations.RenameField(model_name='case', old_name='tag', new_name='tags'),
        migrations.RenameField(model_name='case', old_name='audited_institution', new_name='audited_institutions'),
        migrations.RenameField(model_name='case', old_name='notified_user', new_name='notified_users'),
        migrations.RenameField(model_name='case', old_name='responsible_user', new_name='responsible_users'),

    ]
