# Generated by Django 3.0.5 on 2020-04-20 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0005_merge_multiple_leaf_nodes'),
        ('institutions', '0007_auto_20200221_1956'),
        ('features', '0002_auto_20200310_0428'),
        ('cases', '0010_auto_20200420_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='audited_institutions',
            field=models.ManyToManyField(blank=True, help_text='Case audits this Institutions.', to='institutions.Institution', verbose_name='Audited institutions'),
        ),
        migrations.AlterField(
            model_name='case',
            name='comments',
            field=models.CharField(blank=True, help_text='Comments for this case.', max_length=256, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='case',
            name='featureoptions',
            field=models.ManyToManyField(blank=True, help_text='Features options for this case.', to='features.FeatureOption', verbose_name='Feature options'),
        ),
        migrations.AlterField(
            model_name='case',
            name='notified_users',
            field=models.ManyToManyField(blank=True, help_text='Users who will receive notifications.', related_name='notified_users', to=settings.AUTH_USER_MODEL, verbose_name='Notified users'),
        ),
        migrations.AlterField(
            model_name='case',
            name='responsible_users',
            field=models.ManyToManyField(blank=True, help_text='Users who is responsible for this case.', related_name='responsible_users', to=settings.AUTH_USER_MODEL, verbose_name='Responsible users'),
        ),
        migrations.AlterField(
            model_name='case',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Choose tags.', to='tags.Tag', verbose_name='Tags'),
        ),
    ]
