# Generated by Django 3.0.3 on 2020-03-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_auto_20200315_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='comments',
            new_name='comment',
        ),
    ]
