# Generated by Django 2.1.3 on 2018-11-27 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0010_auto_20181126_0302"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="institution",
            options={
                "ordering": ["name"],
                "verbose_name": "Institution",
                "verbose_name_plural": "Institutions",
            },
        ),
    ]
