# Generated by Django 3.0.3 on 2020-03-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_auto_20200315_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='comment',
        ),
        migrations.AddField(
            model_name='case',
            name='comments',
            field=models.CharField(blank=True, help_text='Comments for this case.', max_length=256, verbose_name='Comments'),
        ),
    ]
