# Generated by Django 3.0.6 on 2020-05-27 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0011_auto_20200420_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='comments',
        ),
        migrations.AddField(
            model_name='case',
            name='comment',
            field=models.CharField(blank=True, help_text='Comment for this case.', max_length=256, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='case',
            name='notified_users',
            field=models.ManyToManyField(blank=True, help_text='Users who will receive notifications.', related_name='notified_about_case_set', to=settings.AUTH_USER_MODEL, verbose_name='Notified users'),
        ),
        migrations.AlterField(
            model_name='case',
            name='responsible_users',
            field=models.ManyToManyField(blank=True, help_text='Users who is responsible for this case.', related_name='responsible_for_case_set', to=settings.AUTH_USER_MODEL, verbose_name='Responsible users'),
        ),
    ]
