# Generated by Django 3.0.3 on 2020-03-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_merge_multiple_leaf_nodes'),
        ('cases', '0012_auto_20200315_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='tag',
        ),
        migrations.AddField(
            model_name='case',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Choose tags.', to='tags.Tag', verbose_name='Tags'),
        ),
    ]
