# Generated by Django 3.0.3 on 2020-03-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0007_auto_20200221_1956'),
        ('features', '0002_auto_20200310_0428'),
        ('cases', '0013_auto_20200315_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='audited_institution',
        ),
        migrations.AddField(
            model_name='case',
            name='audited_institutions',
            field=models.ManyToManyField(blank=True, help_text='Case audits this Institutions.', to='institutions.Institution', verbose_name='Audited institutions'),
        ),
        migrations.AlterField(
            model_name='case',
            name='featureoptions',
            field=models.ManyToManyField(blank=True, help_text='Features options for this case.', to='features.FeatureOption', verbose_name='Feature options'),
        ),
    ]
