# Generated by Django 3.0.3 on 2020-03-15 12:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0014_auto_20200315_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='notified_user',
        ),
        migrations.AddField(
            model_name='case',
            name='notified_users',
            field=models.ManyToManyField(blank=True, help_text='Users who will receive notification.', related_name='notified_users', to=settings.AUTH_USER_MODEL, verbose_name='Notified users'),
        ),
    ]
