# Generated by Django 3.0.3 on 2020-03-15 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0015_auto_20200315_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='notified_users',
            field=models.ManyToManyField(blank=True, help_text='Users who will receive notifications.', related_name='notified_users', to=settings.AUTH_USER_MODEL, verbose_name='Notified users'),
        ),
    ]
