# Generated by Django 3.0.3 on 2020-03-15 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0016_auto_20200315_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='responsible_user',
        ),
        migrations.AddField(
            model_name='case',
            name='responsible_users',
            field=models.ManyToManyField(blank=True, help_text='Users who is responsible for this case.', related_name='responsible_users', to=settings.AUTH_USER_MODEL, verbose_name='Responsible users'),
        ),
    ]
