# Generated by Django 3.0.3 on 2020-03-25 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('cases', '0001_initial'), ('cases', '0002_case_auditedinstitution'), ('cases', '0003_auto_20200109_1348'), ('cases', '0004_auto_20200114_0211'), ('cases', '0005_auto_20200122_2041'), ('cases', '0006_auto_20200126_0711'), ('cases', '0007_auto_20200221_1956'), ('cases', '0008_auto_20200308_2139'), ('cases', '0009_case_featureoptions'), ('cases', '0010_auto_20200315_1129'), ('cases', '0011_auto_20200315_1157'), ('cases', '0012_auto_20200315_1204'), ('cases', '0013_auto_20200315_1211'), ('cases', '0014_auto_20200315_1219'), ('cases', '0015_auto_20200315_1235'), ('cases', '0016_auto_20200315_1241'), ('cases', '0017_auto_20200315_1322')]

    initial = True

    dependencies = [
        ('features', '0002_auto_20200310_0428'),
        ('tags', '0003_tagnamespace_prefix'),
        ('tags', '0005_merge_multiple_leaf_nodes'),
        ('features', '0001_initial'),
        ('institutions', '0001_initial'),
        ('institutions', '0007_auto_20200221_1956'),
        ('institutions', '0004_auto_20200112_2019'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Date of the modification')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('name', models.CharField(help_text="Case's name.", max_length=256, verbose_name='Name')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='case_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='case_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('featureoptions', models.ManyToManyField(blank=True, help_text='Features options for this case.', to='features.FeatureOption', verbose_name='Feature options')),
                ('comments', models.CharField(blank=True, help_text='Comments for this case.', max_length=256, verbose_name='Comments')),
                ('tags', models.ManyToManyField(blank=True, help_text='Choose tags.', to='tags.Tag', verbose_name='Tags')),
                ('audited_institutions', models.ManyToManyField(blank=True, help_text='Case audits this Institutions.', to='institutions.Institution', verbose_name='Audited institutions')),
                ('notified_users', models.ManyToManyField(blank=True, help_text='Users who will receive notifications.', related_name='notified_users', to=settings.AUTH_USER_MODEL, verbose_name='Notified users')),
                ('responsible_users', models.ManyToManyField(blank=True, help_text='Users who is responsible for this case.', related_name='responsible_users', to=settings.AUTH_USER_MODEL, verbose_name='Responsible users')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
