# Generated by Django 3.0.1 on 2020-01-03 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0001_initial'),
        ('channel', '0001_initial'),
        ('case', '0002_case_auditedinstitution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifiedOn', models.DateTimeField(auto_now=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('direction', models.TextField(choices=[('IN', 'Received'), ('OUT', 'Sent')], default='IN', max_length=3)),
                ('name', models.CharField(max_length=256)),
                ('final', models.BooleanField()),
                ('date', models.DateTimeField()),
                ('identifier', models.CharField(max_length=256)),
                ('ordering', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=256)),
                ('excerpt', models.CharField(max_length=256)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='institution.AddressData')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='case.Case')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='channel.Channel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
