# Generated by Django 2.0.5 on 2018-11-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20180614_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='attachment',
            field=models.FileField(blank=True, upload_to='', verbose_name='Attachment'),
        ),
    ]
