# Generated by Django 2.1.3 on 2018-11-08 01:24

from django.db import migrations


def migrate_tags_from_letter_to_case(apps, schema_editor):
    Letter = apps.get_model('cases', 'Letter')
    for row in Letter.objects.exclude(tags=None).all():
        if not row.institution:
            continue
        for tag in row.tags.all():
            row.institution.tags.add(tag)
        row.institution.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_auto_20181107_2349'),
    ]

    operations = [
        migrations.RunPython(migrate_tags_from_letter_to_case),
        migrations.RemoveField(
            model_name='letter',
            name='tags',
        ),
    ]
