# Generated by Django 2.1.3 on 2018-11-26 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_remove_letter_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'ordering': ['-data'], 'verbose_name': 'Letter', 'verbose_name_plural': 'Letters'},
        ),
    ]
