# Generated by Django 2.1.3 on 2018-11-26 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0008_auto_20181126_0254"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="audited_institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cases.Institution",
                verbose_name="Audited institution",
            ),
        ),
    ]
