# Generated by Django 2.1.3 on 2018-11-26 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_case_audited_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='institution',
            field=models.ForeignKey(help_text='From whom / to whom', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.Institution', verbose_name='Institution'),
        ),
    ]
