# Generated by Django 2.2.9 on 2021-01-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0013_auto_20190302_0518"),
    ]

    operations = [
        migrations.AddField(
            model_name="letter",
            name="event",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Event time"
            ),
        ),
    ]
