# Generated by Django 3.0.1 on 2020-01-09 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=256)),
                ('data', models.DateTimeField()),
                ('comment', models.CharField(max_length=256)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cases.Case')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
