# Generated by Django 3.0.6 on 2020-05-28 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_auto_20200420_0717'),
        ('events', '0006_Plural_form_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cases',
        ),
        migrations.RemoveField(
            model_name='event',
            name='comments',
        ),
        migrations.AddField(
            model_name='event',
            name='case',
            field=models.ForeignKey(default='', help_text='Case for this event.', on_delete=django.db.models.deletion.DO_NOTHING, to='cases.Case', verbose_name='Case'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='comment',
            field=models.CharField(default='', help_text='Comment text.', max_length=256, verbose_name='Comment'),
            preserve_default=False,
        ),
    ]
