# Generated by Django 3.0.2 on 2020-01-31 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_auto_20200109_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='active',
            field=models.BooleanField(default=False, help_text='Make active.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='max_items',
            field=models.IntegerField(default=1, help_text='Maximum number of items.', verbose_name='Max. items'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='min_items',
            field=models.IntegerField(default=1, help_text='Minimum number of items.', verbose_name='Min. items'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='name',
            field=models.CharField(help_text='Name of dictionary.', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='dictionary',
            field=models.ForeignKey(help_text='Name of dictionary.', on_delete=django.db.models.deletion.CASCADE, to='dictionaries.Dictionary', verbose_name='Dictionary'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(help_text='Name of feature.', max_length=100, verbose_name='Name'),
        ),
    ]
