# Generated by Django 3.0.2 on 2020-01-31 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0003_auto_20200131_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='dictionary',
            field=models.ForeignKey(help_text='Related dictionary.', on_delete=django.db.models.deletion.CASCADE, to='dictionaries.Dictionary', verbose_name='Dictionary'),
        ),
    ]
