# Generated by Django 2.0.5 on 2018-05-18 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cases.Institution'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
