# Generated by Django 3.0.1 on 2020-01-09 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TagNamespace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=256)),
                ('color', models.CharField(default='000000', max_length=6, validators=[django.core.validators.RegexValidator(code='Non_RGB_hex', message='Field must be hexadecimal RGB color', regex='^(?:[a-f0-9]{6})|(?:[A-F0-9]{6})$')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
