# Generated by Django 3.0.1 on 2020-01-09 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20200104_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag_string',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='object_id',
        ),
    ]
