# Generated by Django 3.0.7 on 2020-06-30 19:08

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teryt_tree', '0007_auto_20191020_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeUnit',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('teryt_tree.jednostkaadministracyjna',),
        ),
    ]
