# Generated by Django 3.0.1 on 2020-01-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0001_initial'),
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='auditedInstitution',
            field=models.ManyToManyField(to='institution.Institution'),
        ),
    ]
