# Generated by Django 3.0.1 on 2020-01-03 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case', '0002_case_auditedinstitution'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='case_createdBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='modifiedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='case_modifiedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='notifiedUser',
            field=models.ManyToManyField(related_name='case_notifiedUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='responsibleUser',
            field=models.ManyToManyField(related_name='case_responsibleUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
