# Generated by Django 3.0.1 on 2020-01-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='auditedInstitution',
            field=models.ManyToManyField(to='institutions.Institution'),
        ),
    ]
