# Generated by Django 3.0.1 on 2020-01-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='audited_institution',
            field=models.ManyToManyField(blank=True, to='institutions.Institution'),
        ),
    ]
