# Generated by Django 3.0.1 on 2020-01-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0003_auto_20200109_0306'),
        ('tags', '0003_auto_20200109_0306'),
        ('institutions', '0002_auto_20200104_2227'),
        ('cases', '0003_auto_20200104_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='letterCount',
        ),
        migrations.RemoveField(
            model_name='case',
            name='noteCount',
        ),
        migrations.AddField(
            model_name='case',
            name='feature',
            field=models.ManyToManyField(blank=True, to='dictionaries.Feature'),
        ),
        migrations.AddField(
            model_name='case',
            name='tag',
            field=models.ManyToManyField(blank=True, to='tags.Tag'),
        ),
        migrations.AlterField(
            model_name='case',
            name='auditedInstitution',
            field=models.ManyToManyField(blank=True, to='institutions.Institution'),
        ),
    ]
