# Generated by Django 3.0.2 on 2020-01-22 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_auto_20200110_0200'),
        ('files', '0002_file_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='letters.Letter'),
        ),
    ]
