# Generated by Django 3.0.7 on 2020-06-25 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0011_auto_20200618_1921'),
        ('files', '0004_auto_20200220_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='letter',
            field=models.ForeignKey(help_text='Related letter.', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='letters.Letter', verbose_name='Letter'),
        ),
    ]
