# Generated by Django 3.0.5 on 2020-05-01 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('files', '0005_auto_20200501_1439'), ('files', '0006_auto_20200501_1442')]

    dependencies = [
        ('files', '0004_auto_20200220_1824'),
        ('letters', '0010_remove_letter_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='letter',
            new_name='letters',
        ),
        migrations.AlterField(
            model_name='file',
            name='letters',
            field=models.ForeignKey(help_text='Related letters.', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='letters.Letter', verbose_name='Letters'),
        ),
    ]
