# Generated by Django 3.0.7 on 2020-06-18 23:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import small_eod.generic.validators


class Migration(migrations.Migration):

    replaces = [('institutions', '0001_initial'), ('institutions', '0002_auto_20200109_1348'), ('institutions', '0003_auto_20200110_0314'), ('institutions', '0004_auto_20200112_2019'), ('institutions', '0005_auto_20200203_0453')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teryt_tree', '0007_auto_20191020_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('flat_no', models.CharField(blank=True, default='', max_length=100)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=100)),
                ('house_no', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('epuap', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(blank=True, max_length=10, validators=[small_eod.generic.validators.ExactLengthsValidator([10]), django.core.validators.RegexValidator('^[0-9]*$')])),
                ('regon', models.CharField(blank=True, max_length=14, validators=[small_eod.generic.validators.ExactLengthsValidator([10, 14]), django.core.validators.RegexValidator('^[0-9]*$')])),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=256)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.AddressData')),
                ('administrative_unit', models.ForeignKey(blank=True, limit_choices_to=models.Q(category__level=3), null=True, on_delete=django.db.models.deletion.CASCADE, to='teryt_tree.JednostkaAdministracyjna')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='institution_created_by', to=settings.AUTH_USER_MODEL)),
                ('external_identifier', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.ExternalIdentifier')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='institution_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
