# Generated by Django 3.0.1 on 2020-01-10 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_auto_20200109_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='administrativeUnit',
            new_name='administrative_unit',
        ),
    ]
