# Generated by Django 3.0.2 on 2020-01-22 00:43

import django.core.validators
from django.db import migrations, models
import small_eod.generic.validators


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_auto_20200112_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressdata',
            name='voivodeship',
        ),
        migrations.AlterField(
            model_name='addressdata',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addressdata',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='addressdata',
            name='epuap',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addressdata',
            name='house_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addressdata',
            name='postal_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addressdata',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='externalidentifier',
            name='nip',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[small_eod.generic.validators.ExactLengthsValidator([10]), django.core.validators.RegexValidator('^\\d*$')]),
        ),
        migrations.AlterField(
            model_name='externalidentifier',
            name='regon',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[small_eod.generic.validators.ExactLengthsValidator([10, 14]), django.core.validators.RegexValidator('^\\d*$')]),
        ),
    ]
