# Generated by Django 3.0.2 on 2020-02-03 04:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import small_eod.generic.validators


class Migration(migrations.Migration):

    dependencies = [
        ('teryt_tree', '0007_auto_20191020_2005'),
        ('institutions', '0004_auto_20200112_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressdata',
            name='voivodeship',
        ),
        migrations.AlterField(
            model_name='addressdata',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='addressdata',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='addressdata',
            name='epuap',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='addressdata',
            name='flat_no',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addressdata',
            name='house_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='addressdata',
            name='postal_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='addressdata',
            name='street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='externalidentifier',
            name='nip',
            field=models.CharField(blank=True, max_length=10, validators=[small_eod.generic.validators.ExactLengthsValidator([10]), django.core.validators.RegexValidator('^[0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='externalidentifier',
            name='regon',
            field=models.CharField(blank=True, max_length=14, validators=[small_eod.generic.validators.ExactLengthsValidator([10, 14]), django.core.validators.RegexValidator('^[0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='institution',
            name='administrative_unit',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(category__level=3), null=True, on_delete=django.db.models.deletion.CASCADE, to='teryt_tree.JednostkaAdministracyjna'),
        ),
    ]
