# Generated by Django 3.0.2 on 2020-01-22 03:35

from django.db import migrations, models
import django.db.models.deletion
import small_eod.institutions.validators


class Migration(migrations.Migration):

    dependencies = [
        ('teryt_tree', '0007_auto_20191020_2005'),
        ('institutions', '0005_auto_20200122_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='administrative_unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teryt_tree.JednostkaAdministracyjna', validators=[small_eod.institutions.validators.validate_level_3]),
        ),
    ]
