# Generated by Django 3.0.3 on 2020-02-20 18:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import small_eod.generic.validators


class Migration(migrations.Migration):

    dependencies = [
        ('teryt_tree', '0007_auto_20191020_2005'),
        ('institutions', '0005_auto_20200203_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressdata',
            name='city',
            field=models.CharField(blank=True, help_text='Name of city.', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='addressdata',
            name='email',
            field=models.EmailField(blank=True, help_text='E-mail address.', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='addressdata',
            name='epuap',
            field=models.CharField(blank=True, help_text='ePUAP address.', max_length=100, verbose_name='ePUAP'),
        ),
        migrations.AlterField(
            model_name='addressdata',
            name='flat_no',
            field=models.CharField(blank=True, help_text='Flat number.', max_length=100, verbose_name='Flat number'),
        ),
        migrations.AlterField(
            model_name='addressdata',
            name='house_no',
            field=models.CharField(blank=True, help_text='House number.', max_length=100, verbose_name='House number'),
        ),
        migrations.AlterField(
            model_name='addressdata',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal code.', max_length=100, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='addressdata',
            name='street',
            field=models.CharField(blank=True, help_text='Name of street.', max_length=100, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='externalidentifier',
            name='nip',
            field=models.CharField(blank=True, help_text='Tax Identification Number.', max_length=10, validators=[small_eod.generic.validators.ExactLengthsValidator([10]), django.core.validators.RegexValidator('^[0-9]*$')], verbose_name='NIP'),
        ),
        migrations.AlterField(
            model_name='externalidentifier',
            name='regon',
            field=models.CharField(blank=True, help_text='Statistical Identification Number.', max_length=14, validators=[small_eod.generic.validators.ExactLengthsValidator([10, 14]), django.core.validators.RegexValidator('^[0-9]*$')], verbose_name='REGON'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='address',
            field=models.OneToOneField(blank=True, help_text='Address of institution.', null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.AddressData', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='administrative_unit',
            field=models.ForeignKey(blank=True, help_text='Administrative division.', limit_choices_to=models.Q(category__level=3), null=True, on_delete=django.db.models.deletion.CASCADE, to='teryt_tree.JednostkaAdministracyjna', verbose_name='Administrative division'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='external_identifier',
            field=models.OneToOneField(blank=True, help_text='External identifier of institution.', null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.ExternalIdentifier', verbose_name='External identifier'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(help_text='Name of institution', max_length=256, verbose_name='Name'),
        ),
    ]
