# Generated by Django 3.0.7 on 2020-06-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_merge_multiple_leaf_nodes'),
        ('institutions', '0008_auto_20200528_1330'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='institution',
        #     name='comment',
        #     field=models.CharField(blank=True, help_text='Comment for this case.', max_length=256, verbose_name='Comment'),
        # ),
        # migrations.AddField(
        #     model_name='institution',
        #     name='tags',
        #     field=models.ManyToManyField(blank=True, help_text='Choose tags.', to='tags.Tag', verbose_name='Tags'),
        # ),
    ]
