# Generated by Django 3.0.7 on 2020-06-30 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_units', '0001_initial'),
        ('institutions', '0009_auto_20200618_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='administrative_unit',
            field=models.ForeignKey(blank=True, help_text='Administrative division.', limit_choices_to=models.Q(category__level=3), null=True, on_delete=django.db.models.deletion.CASCADE, to='administrative_units.AdministrativeUnit', verbose_name='Administrative division'),
        ),
    ]
