# Generated by Django 3.0.3 on 2020-02-21 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_auto_20200126_0711'),
        ('notes', '0002_auto_20200109_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='case',
            field=models.ForeignKey(help_text='Related case.', on_delete=django.db.models.deletion.DO_NOTHING, to='cases.Case', verbose_name='Case'),
        ),
        migrations.AlterField(
            model_name='note',
            name='comment',
            field=models.CharField(max_length=256, verbose_name='Comment'),
        ),
    ]
