# Generated by Django 3.0.3 on 2020-03-04 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20200221_1929'),
        ('notes', '0003_auto_20200221_1956'),
    ]

    operations = [
    ]
