# Generated by Django 3.0.1 on 2020-01-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20200109_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagnamespace',
            name='prefix',
            field=models.CharField(default='test', help_text='This namespace will match each tag starting with `prefix`.', max_length=254),
            preserve_default=False,
        ),
    ]
