# Generated by Django 3.0.3 on 2020-03-04 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_auto_20200221_1956'),
        ('tags', '0004_auto_20200221_1937'),
    ]

    operations = [
    ]
