# Generated by Django 3.1.1 on 2020-09-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_merge_multiple_leaf_nodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Tag'),
        ),
    ]
