# Generated by Django 3.0.7 on 2020-06-18 23:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('letters', '0001_initial'), ('letters', '0002_auto_20200109_1348'), ('letters', '0003_auto_20200110_0200'), ('letters', '0004_auto_20200220_1923'), ('letters', '0005_auto_20200221_1920'), ('letters', '0004_auto_20200221_1956'), ('letters', '0006_merge_multiple_leaf_nodes'), ('letters', '0006_auto_20200224_1305'), ('letters', '0007_merge_20200307_2119'), ('letters', '0008_letter_description'), ('letters', '0009_auto_20200308_2139'), ('letters', '0010_remove_letter_address')]

    dependencies = [
        ('institutions', '0005_auto_20200203_0453'),
        ('cases', '0006_auto_20200126_0711'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0002_auto_20200109_1348'),
        ('channels', '0005_auto_20200125_1954'),
        ('cases', '0002_case_auditedinstitution'),
        ('channels', '0006_auto_20200221_1956'),
        ('channels', '0001_initial'),
        ('institutions', '0001_initial'),
        ('cases', '0007_auto_20200221_1956'),
        ('institutions', '0007_auto_20200221_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Description of letter.', max_length=256, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Date of the modification')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('direction', models.TextField(choices=[('IN', 'Received'), ('OUT', 'Sent')], default='IN', help_text='Direction for letter.', max_length=3, verbose_name='Direction')),
                ('name', models.CharField(help_text='Description of the letter.', max_length=256, verbose_name='Description')),
                ('final', models.BooleanField(default=True, help_text='Indicates whether the document has final content or is, for example, a draft', verbose_name='Final version')),
                ('date', models.DateTimeField(default=datetime.datetime.now, help_text='Date of sending or receiving.', verbose_name='Date')),
                ('identifier', models.CharField(blank=True, help_text='Identifier of letter.', max_length=256, verbose_name='Identifier')),
                ('ordering', models.IntegerField(default=0, help_text='Order of letter.', verbose_name='Ordering')),
                ('comment', models.CharField(blank=True, help_text='Comment for letter.', max_length=256, verbose_name='Comment')),
                ('excerpt', models.CharField(blank=True, help_text='Excerpt of letter.', max_length=256, verbose_name='Excerpt')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cases.Case', verbose_name='Case')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='channels.Channel', verbose_name='Channel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='letter_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='institutions.Institution', verbose_name='Institution')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='letter_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='letters.Description', verbose_name='Description of letter.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
