# Generated by Django 3.0.1 on 2020-01-10 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_auto_20200109_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='text',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='description',
            name='letter',
        ),
    ]
