# Generated by Django 3.0.3 on 2020-02-20 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_auto_20200203_0453'),
        ('channels', '0005_auto_20200125_1954'),
        ('cases', '0006_auto_20200126_0711'),
        ('letters', '0003_auto_20200110_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='name',
            field=models.CharField(help_text='Description of letter.', max_length=256, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='institutions.AddressData', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cases.Case', verbose_name='Case'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='channels.Channel', verbose_name='Channel'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='comment',
            field=models.CharField(help_text='Comment for letter.', max_length=256, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='date',
            field=models.DateTimeField(help_text='Date of sending or receiving.', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='direction',
            field=models.TextField(choices=[('IN', 'Received'), ('OUT', 'Sent')], default='IN', help_text='Direction for letter.', max_length=3, verbose_name='Direction'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='excerpt',
            field=models.CharField(help_text='Excerpt of letter.', max_length=256, verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='identifier',
            field=models.CharField(help_text='Identifier of letter.', max_length=256, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='institutions.Institution', verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='name',
            field=models.CharField(help_text='Description of the letter.', max_length=256, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='ordering',
            field=models.IntegerField(default=0, help_text='Order of letter', verbose_name='Ordering'),
        ),
    ]
