# Generated by Django 3.0.3 on 2020-02-06 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_auto_20200110_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='letter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='letters.Letter'),
            preserve_default=False,
        ),
    ]
