# Generated by Django 3.0.3 on 2020-02-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0004_auto_20200220_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='ordering',
            field=models.IntegerField(default=0, help_text='Order of letter.', verbose_name='Ordering'),
        ),
    ]
