# Generated by Django 3.0.3 on 2020-03-07 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0006_auto_20200224_1305'),
        ('letters', '0006_merge_multiple_leaf_nodes'),
    ]

    operations = [
    ]
