# Generated by Django 3.0.3 on 2020-03-07 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0007_merge_20200307_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='letters.Description', verbose_name='Description of letter.'),
        ),
    ]
