# Generated by Django 3.0.3 on 2020-03-08 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0009_auto_20200308_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='address',
        ),
    ]
