# Generated by Django 3.0.7 on 2020-06-18 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0010_remove_letter_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Type of letter', max_length=256, verbose_name='Document type')),
            ],
        ),
        migrations.RemoveField(
            model_name='letter',
            name='description',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='name',
        ),
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.AddField(
            model_name='letter',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='letters.DocumentType', verbose_name='Document type of letter.'),
        ),
    ]
