# Generated by Django 3.0.6 on 2020-06-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0011_auto_20200618_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='identifier',
        ),
        migrations.AddField(
            model_name='letter',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Reference number of letter.', max_length=256, verbose_name='Reference number'),
        ),
    ]
