# Generated by Django 3.0.1 on 2020-01-09 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teryt_tree', '0007_auto_20191020_2005'),
        ('institutions', '0002_auto_20200104_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='administrativeUnit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teryt_tree.JednostkaAdministracyjna'),
        ),
        migrations.DeleteModel(
            name='AdministrativeUnit',
        ),
    ]
