name: Load-balancer image

on:
  push:
    branches:
      - dev
    paths:
    - 'balancer/**'
    - '.github/**'
    - 'Makefile'
  pull_request:
    paths:
    - 'balancer/**'
    - '.github/**'
    - 'Makefile'
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
    - name: Build production image
      run: make build_balancer
    - name: "Docker login"
      if: github.ref == 'refs/heads/dev'
      env:
        DOCKER_REGISTRY_URL: docker-registry.siecobywatelska.pl
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: echo "${DOCKER_PASSWORD}" | docker login -u ${DOCKER_USERNAME} --password-stdin ${DOCKER_REGISTRY_URL}
    - name: Push image
      if: github.ref == 'refs/heads/dev'
      run: make push_balancer
