name: YAML files

on:
  push:
    paths:
    - 'docs/**'
  pull_request:
    paths:
    - 'docs/**'

jobs:
  lint_speccy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
    - name: Lint with Speccy
      run: |
        find $PWD -name 'swagger.yaml' | while read FILE; do
          docker run -v ${FILE}:/swagger.yaml --rm wework/speccy lint /swagger.yaml;
        done;

  lint_openapi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
    - name: Lint with openapi-spec-validator
      run: |
        find $PWD -name 'swagger.yaml' | while read FILE; do
          docker run -v ${FILE}:/swagger.yaml --rm p1c2u/openapi-spec-validator /swagger.yaml;
        done;
