# Generated by Django 3.0.1 on 2020-01-03 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifiedOn', models.DateTimeField(auto_now=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(choices=[('WHOSE', 'Do kogo należy sprawa'), ('WSCOPE', 'Jaki zakres sprawy'), ('ISCOPE', 'Bezczynność w jakim zakresie'), ('DSCOPE', 'Decyzja w jakim zakresie'), ('INFOT', 'Informacja udzielona w którym momencie'), ('STATUS', 'Status')], max_length=100)),
                ('minItems', models.IntegerField(default=1)),
                ('maxItems', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.Case')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DictValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.BooleanField(default=False)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Dictionary')),
            ],
        ),
    ]
