# Generated by Django 3.0.1 on 2020-01-04 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_auto_20200103_1715'),
        ('dictionary', '0002_auto_20200103_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('WHOSE', 'Do kogo należy sprawa'), ('WSCOPE', 'Jaki zakres sprawy'), ('ISCOPE', 'Bezczynność w jakim zakresie'), ('DSCOPE', 'Decyzja w jakim zakresie'), ('INFOT', 'Informacja udzielona w którym momencie'), ('STATUS', 'Status')], max_length=6)),
                ('minItems', models.IntegerField(default=1)),
                ('maxItems', models.IntegerField(default=1)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.Case')),
            ],
        ),
        migrations.RemoveField(
            model_name='dictionary',
            name='maxItems',
        ),
        migrations.RemoveField(
            model_name='dictionary',
            name='minItems',
        ),
        migrations.AddField(
            model_name='dictionary',
            name='type',
            field=models.CharField(choices=[('WHOSE', 'Do kogo należy sprawa'), ('WSCOPE', 'Jaki zakres sprawy'), ('ISCOPE', 'Bezczynność w jakim zakresie'), ('DSCOPE', 'Decyzja w jakim zakresie'), ('INFOT', 'Informacja udzielona w którym momencie'), ('STATUS', 'Status')], default='WHOSE', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='DictValue',
        ),
    ]
